title: Grex Docs
description: Official Documentation for Grex, the Modern Tabbed File Search Tool.
theme: minima
header_pages:
  - usage.md
  - features.md
  - architecture.md
  - build-and-test.md
logo: /assets/img/logo.png
plugins:
  - jekyll-feed

